sudo: false
addons:
  apt:
    packages:
    - git
language: java
jdk: oraclejdk8
env: TERM=dumb
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - git config user.email "d.dubson@gmail.com"
  - git config user.name "Dmitriy Dubson"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
install:
  - echo "skip default gradlew assemble"
script:
  - ./gradlew release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password